name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test3  # Specify your active branches here
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run on a Windows-hosted GitHub Actions runner

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python 3.11.3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'  # Ensuring Python 3.11.3 is used

    # Install dependencies (example for Python)
    - name: Install dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\activate  # Windows-specific virtual environment activation
        pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
        .\venv\Scripts\activate  # Windows-specific virtual environment activation
        pytest -v

  deploy:
    runs-on: windows-latest  # Ensure deployment also runs on Windows runner
    needs: build  # Ensures 'build' job runs first

    steps:
    - name: Deploy application
      run: |
        echo "Deploying to the server..."
        # Add your deployment steps here
